services:
  openldap:
    image: osixia/openldap
    environment:
      - LDAP_LOG_LEVEL=0
      - LDAP_TLS_VERIFY_CLIENT=never

  openldap-prepare:
    build:
      context: .
      dockerfile: dockerfiles/openldap-prepare.dockerfile
    depends_on:
      - openldap

  ruby-2.7-activemodel-7:
    build:
      context: .
      dockerfile: dockerfiles/ruby.dockerfile
      args:
        FROM: ruby:2.7
        GEMFILE: Gemfile.activemodel7
    depends_on:
      - openldap-prepare
    volumes:
      - .:/source:delegated

  ruby-3.0-activemodel-7:
    build:
      context: .
      dockerfile: dockerfiles/ruby.dockerfile
      args:
        FROM: ruby:3.0
        GEMFILE: Gemfile.activemodel7
    depends_on:
      - openldap-prepare
    volumes:
      - .:/source:delegated

  ruby-3.1-activemodel-7:
    build:
      context: .
      dockerfile: dockerfiles/ruby.dockerfile
      args:
        FROM: ruby:3.1
        GEMFILE: Gemfile.activemodel7
    depends_on:
      - openldap-prepare
    volumes:
      - .:/source:delegated

  ruby-3.2-activemodel-7:
    build:
      context: .
      dockerfile: dockerfiles/ruby.dockerfile
      args:
        FROM: ruby:3.2
        GEMFILE: Gemfile.activemodel7
    depends_on:
      - openldap-prepare
    volumes:
      - .:/source:delegated

  ruby-3.3-activemodel-7:
    build:
      context: .
      dockerfile: dockerfiles/ruby.dockerfile
      args:
        FROM: ruby:3.3
        GEMFILE: Gemfile.activemodel7
    depends_on:
      - openldap-prepare
    volumes:
      - .:/source:delegated

  jruby-9-activemodel-7:
    build:
      context: .
      dockerfile: dockerfiles/ruby.dockerfile
      args:
        FROM: jruby:9
        GEMFILE: Gemfile.activemodel7
    depends_on:
      - openldap-prepare
    volumes:
      - .:/source:delegated
