#!/usr/bin/ruby -W0
$: << "../lib"

require 'activeldap'
require 'objects/user'
require 'objects/group'
require 'password'

if ARGV.size != 1
  puts "Usage:\n#{$0} <name>\n"
  exit 1
end

puts "Deleting group #{ARGV[0]}"
pwb = Proc.new {
  Password.get('Password: ')
}
ActiveLDAP::Base.connect(:user => 'root', :password_block => pwb, :allow_anonymous => false)
group = Group.new(ARGV[0])
p group
group.validate
group.delete
exit 0


