#!/usr/bin/ruby -W0

base = File.expand_path(File.join(File.dirname(__FILE__), ".."))
$LOAD_PATH << File.join(base, "lib")
$LOAD_PATH << File.join(base, "examples")

require 'active_ldap'
require 'objects/user'
require 'objects/group'

argv, opts, options = ActiveLdap::Command.parse_options do |opts, options|
  opts.banner += " GROUP_NAME GID_NUMBER"
end

if argv.size == 2
  name, gid = argv
else
  $stderr.puts opts
  exit 1
end

pwb = Proc.new do |user|
  ActiveLdap::Command.read_password("[#{user}] Password: ")
end

ActiveLdap::Base.setup_connection(:password_block => pwb,
                                  :allow_anonymous => false)


unless Group.exists?(name)
  $stderr.puts("Group #{name} doesn't exist.")
  exit 1
end

group = Group.find(name)
group.gid_number = gid

unless group.save
  puts "failed"
  puts group.errors.full_messages
  exit 1
end
