#!/usr/bin/ruby -W0

base = File.expand_path(File.join(File.dirname(__FILE__), ".."))
$LOAD_PATH << File.join(base, "lib")
$LOAD_PATH << File.join(base, "examples")

require 'active_ldap'
require 'objects/user'
require 'objects/group'

argv, opts, options = ActiveLdap::Command.parse_options do |opts, options|
  opts.banner += " GROUP_NAME"
end

if argv.size == 1
  name = argv.shift
else
  $stderr.puts opts
  exit 1
end

pwb = Proc.new do |user|
  ActiveLdap::Command.read_password("[#{user}] Password: ")
end

ActiveLdap::Base.establish_connection(:password_block => pwb,
                                      :allow_anonymous => false)

if Group.exists?(name)
  $stderr.puts("Group #{name} already exists.")
  exit 1
end

group = Group.new(name)
group.gid_number = 9000

unless group.save
  puts "failed"
  puts group.errors.full_messages
  exit 1
end
