#!/usr/bin/ruby -W0
$: << "../lib"

require 'activeldap'
require 'objects/user'
require 'objects/group'
require 'password'

(printf($stderr, "Usage:\n%s name cn uid\n", $0); exit 1) if ARGV.size != 3

puts "Changing user #{ARGV[0]}"
pwb = Proc.new {
  Password.get('Password: ')
}
Log4r::Logger.root.level = Log4r::DEBUG
ActiveLDAP::Base.connect(:password_block => pwb, :allow_anonymous => false)
user = User.new(ARGV[0])
user.cn = ARGV[1]
user.uidNumber = ARGV[2]
user.gidNumber = ARGV[2]
user.write
puts "success"
exit 0


